### ISSUE TITLE
코드 주석 

### ISSUE THREAD

**Issue by kmu-yoonsh** [Dokey2017capstone/Okey_capstone2#10]
SoftKeyboard.java

isHangulKey()과 같이 외부에서 가져다 사용한 코드의 경우, 그 의미를 어려운 코드라면 반드시 주석을 삽입해야 합니다. 
더불어 해당 코드가 현재 진행중인 프로젝트의 코딩룰과 다른 룰을 사용할 경우, 
리팩토링하는 것이 좋습니다.

**Comment by sksss123** [comment]
주석 추가 완료
